### ISSUE TITLE
Please provide the binaries on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [Lescovex/LSCX#15]
Please provide the binaries on GitHub Releases at https://github.com/Lescovex/LSCX/releases rather than inside the git repository. Thank you very much.

Reference:
https://github.com/AppImage/appimage.github.io/pull/816

**Comment by nOsDelAbismo** [comment]
we will do thanks

**Comment by nOsDelAbismo** [comment]
ready

**Comment by probonopd** [comment]
Thank you very much.
